name: Delete Submodule

on:
  workflow_dispatch:

jobs:
  delete-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Delete submodule
        run: |
          # 删除子模块目录
          rm -rf libs/hbb_common
          # 删除 .gitmodules 文件
          rm -f .gitmodules
          # 删除 .git/modules 中的记录
          rm -rf .git/modules/libs/hbb_common
          
          # 添加所有修改
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Remove hbb_common submodule"
          git push
